### PR TITLE
feat: new module hello

### PR DESCRIPTION
**Pull request by adityabisoi**
The PR closes issue #7. I have added the hello module. It uses a ```greeting``` and a ```response``` list to determine the queries and responses related to "hello".

### CODE REVIEW

**Comment by adityabisoi** [comment]
@swapagarwal  please review this. Thanks.

**Review by RohitRathore1 — APPROVED** [review]

**Review by RohitRathore1 — CHANGES_REQUESTED** [review]
These are queries that will get mapped to one intent by the core. 
  `greeting=['hello', 'hi', 'hey']`

**Comment by adityabisoi** [comment]
@TeAmP0is0N can you please be more specific? I am not getting you.

**Comment by RohitRathore1** [comment]
@adityabisoi I meant that all queries are not needed here otherwise it will get get mapped to one intent by core.

**Comment by adityabisoi** [comment]
@TeAmP0is0N I have made the necessary changes. Please review.

**Review by RohitRathore1 — APPROVED** [review]

**Comment by swapagarwal** [comment]
@adityabisoi As discussed, please create another PR allowing maintainers to edit.

**Comment by adityabisoi** [comment]
@swapagarwal Already done !

**Pull request closed without merging**
