### PR TITLE
Add new module: bye #4 Resolved

### LINKED ISSUE #4: Add new module: bye
https://github.com/the-vision/jarvis-telegram/wiki

### PR DESCRIPTION
**Pull request by hritikksingh**
**FIxes #4** 

- FIles changed : **_Modules.py_**
- Added functionality in the modules.py to reply to BYE message input and send a bye GIF.

@TeAmP0is0N please review my PR.

### CODE REVIEW

**Review by sgpritam — APPROVED** [review]

**Comment by hritikksingh** [comment]
@TeAmP0is0N if changes are good can this be merged into the master...

**Comment by swapagarwal** [comment]
Waiting for the-vision/jarvis-core#4 to be resolved.

**Comment by hritikksingh** [comment]
@swapagarwal @TeAmP0is0N  the-vision/jarvis-core #4  issue is not being updated with the work progress, can I have a try on that.

**Comment by swapagarwal** [comment]
Thanks @hritikpapa! 👍

**Comment by hritikksingh** [comment]
> Thanks @hritikpapa! 👍

My pleasure @swapagarwal

**Pull request merged**
