### PR TITLE
dice module added

### LINKED ISSUE #41: Add new module: dice
A new dice module can be added, with a probability of each face being 1/6.
I can work on this.

### PR DESCRIPTION
**Pull request by adityabisoi**
Closes #41 

Dice module added, which responds with a face of a dice on command.

@swapagarwal @TeAmP0is0N Please review.

### CODE REVIEW

**Review by RohitRathore1 — APPROVED** [review]

**Comment by swapagarwal** [comment]
Needs a corresponding intent in core before merging.

**Comment by adityabisoi** [comment]
@swapagarwal The core already has a dice intent. Thanks.

**Comment by swapagarwal** [comment]
Oops, my bad! 😅

**Comment by swapagarwal** [comment]
Thanks @adityabisoi! 👍

**Pull request merged**
